# Available commands : https://nikitabobko.github.io/AeroSpace/commands

after-startup-command = []

# open AeroSpace.app to start
start-at-login = false

# tiles|accordion
default-root-container-layout = 'tiles'

# horizontal|vertical|auto
default-root-container-orientation = 'auto'

# mouse follows monitor focus
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# offset when in accordion layout
accordion-padding = 10

# simplify tree (differs from how i3 works)
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-f = 'fullscreen' # toggle zoom

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'

    alt-ctrl-1 = ['move-node-to-workspace 1', 'workspace 1']
    alt-ctrl-2 = ['move-node-to-workspace 2', 'workspace 2']
    alt-ctrl-3 = ['move-node-to-workspace 3', 'workspace 3']
    alt-ctrl-4 = ['move-node-to-workspace 4', 'workspace 4']
    alt-ctrl-5 = ['move-node-to-workspace 5', 'workspace 5']
    alt-ctrl-6 = ['move-node-to-workspace 6', 'workspace 6']
    alt-ctrl-7 = ['move-node-to-workspace 7', 'workspace 7']
    alt-ctrl-8 = ['move-node-to-workspace 8', 'workspace 8']
    alt-ctrl-9 = ['move-node-to-workspace 9', 'workspace 9']
    alt-ctrl-0 = ['move-node-to-workspace 10', 'workspace 10']

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'focus-monitor --wrap-around next'

    # activate bindings in mode below
    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # toggle floating window

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']

[workspace-to-monitor-force-assignment]
    # these workspaces stay on main monitor
    1 = 'main'
    2 = 'main'
    3 = 'main'
    4 = 'main'
    5 = 'main'
    6 = 'main'

    # these move to secondary when it is connected
    7 = ['secondary', 'main']
    8 = ['secondary', 'main']
    9 = ['secondary', 'main']
    10 = ['secondary', 'main']
