source = ~/.config/hypr/catppuccin-frappe.conf

$font = MesloLGS Nerd Font

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, linear
    animation = inputField, 0
    animation = inputFieldColors, 0
    animation = inputFieldFade, 0
    animation = inputFieldDots, 0
    animation = inputFieldWidth, 0
}

background {
    monitor =
    path = ~/dotfiles/assets/wallpapers/horsetooth2.jpg
    blur_passes = 2
    blur_size = 7
    contrast = 0.8
    brightness = 1
    vibrancy = 0
    vibrancy_darkness = 0
}

# box behind the username + password input
shape {
    monitor =
    size = 38%, 500
    color = $base
    rounding = 25

    position = 0, 0
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 30%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $blue
    check_color = $yellow
    fail_color = $red

    font_color = $text
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = <span foreground="##838ba7">Enter password...</span> # catppuccin-frappe overlay1
    check_text = Authenticating...
    fail_text = $PAMFAIL

    dots_spacing = 0.3
    dots_center = false

    position = 0, -80
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12
    font_size = 80
    font_family = $font
    color = $lavender

    position = -30, -20
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 30
    font_family = $font
    color = $lavender

    position = -30, -170
    halign = right
    valign = top
}

# USER
label {
    monitor =
    text =  $DESC
    font_size = 46
    font_family = $font
    color = $blue

    position = 0, 80
    halign = center
    valign = center
}
